# Generated by Django 5.0.6 on 2024-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_imagemodel_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
