# Generated by Django 5.0.2 on 2024-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_imagemodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='trash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
